# Query for extracting the prior task for the specific cutting verb
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX cut: <http://www.ease-crc.org/ont/food_cutting#>
PREFIX soma: <http://www.ease-crc.org/ont/SOMA.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?res WHERE {
	${verb} rdfs:subClassOf* ?sub.
	?sub owl:onProperty cut:requiresPriorTask .
	?sub owl:someValuesFrom ?priortask.
	BIND(REPLACE(STR(?priortask), "^.*[#/]", "") AS ?res).
}