name: Reuse CI
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:
  
jobs:
  Build_deps:
    uses: ./.github/workflows/build_dependencies.yml

  Build_and_run_Tests:
    needs: Build_deps
    runs-on: ubuntu-20.04
    steps:

        # --- Setup ROS ---
      - name: load ros and deps
        uses: actions/cache/restore@v3
        with:
            path: ~/.ros
            key: ros

        # --- Checkout Repos ---
      - name: Checkout pycram
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/pycram'
          submodules: recursive
      - name: Checkout iai_maps
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/iai_maps'
          repository: code-iai/iai_maps
          ref: master
      - name: Checkout iai_robots
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/iai_robots'
          repository: code-iai/iai_robots
          ref: master
      - name: Checkout pr2_common
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/pr2_common'
          repository: PR2/pr2_common
          ref: master
      - name: Checkout kdl_ik_service
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/kdl_ik_service'
          repository: cram2/kdl_ik_service
          ref: master
      - name: Checkout pr2_kinematics
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/pr2_kinematics'
          repository: PR2/pr2_kinematics
          ref: kinetic-devel

        
        
        
        # --- Install Requirements ---
      - name: load pip
        uses: actions/cache/restore@v3
        with:
            path: ~/.cache/pip
            key: pip


        # --- Start Ros Core
      - name: start roscore
        run: |
          roslaunch pycram ik_and_description.launch &

        # --- Run Tests ---
      - name: Run Tests
        run: |
          roscd pycram
          pytest -v test
