name: Reuse CI
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master
      - dev
jobs:
  Build_deps:
    uses: ./.github/workflows/build_dependencies.yml

  Build_and_run_Tests:
    needs: Build_deps
    runs-on: ubuntu-20.04
    steps:

        # --- Setup ROS ---
      - name: load ros and deps
        uses: actions/cache/restore@v3
        with:
            path: ~/ros
            key: ros

        # --- Checkout Repos ---
      - name: Checkout pycram
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/pycram'
          submodules: recursive
      - name: Checkout iai_maps
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/iai_maps'
          repository: code-iai/iai_maps
          ref: master
      - name: Checkout iai_robots
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/iai_robots'
          repository: code-iai/iai_robots
          ref: master
      - name: Checkout pr2_common
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/pr2_common'
          repository: PR2/pr2_common
          ref: master
      - name: Checkout kdl_ik_service
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/kdl_ik_service'
          repository: cram2/kdl_ik_service
          ref: master
      - name: Checkout pr2_kinematics
        uses: actions/checkout@v3
        with:
          path: 'ros_ws/src/pr2_kinematics'
          repository: PR2/pr2_kinematics
          ref: kinetic-devel

        
        
        # --- Build Workspace ---
      - name: build and source workspace
        run: |
          cd ros_ws
          catkin_make
          echo 'export ROS_HOSTNAME=localhost' >> ~/.bashrc
          echo 'source $GITHUB_WORKSPACE/ros_ws/devel/setup.bash' >> ~/.bashrc
        
        # --- Install Requirements ---
      - name: Upgrade pip
        run: |
          sudo pip3 install --upgrade pip
      - name: Install requirements
        run: |
          cd $GITHUB_WORKSPACE/ros_ws/src/pycram
          sudo pip3 install -r requirements.txt
      - name: install additional requirements
        run: |
          sudo pip3 install --ignore-installed pytest pyjpt mlflow
        # --- Start Ros Core
      - name: start roscore
        run: |
          roslaunch pycram ik_and_description.launch &

        # --- Run Tests ---
      - name: Run Tests
        run: |
          roscd pycram
          pytest -v test
