name: hopeful_CI
defaults:
  run:
    shell: bash -ieo pipefail {0}

on: 
  push:
    branches: 
      - dev
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        required: false
        default: false
        description: 'Run tmate session'

jobs:
  container-test-job:
    runs-on: ubuntu-20.04
    container: 
      image: leoaung/testing_ci:two
      ports:
        - 11311
      volumes:
        - docker_volume:/opt/ros/overlay_ws
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Set up sources
        run: |
          sudo -s
          source /opt/ros/noetic/setup.bash
          cd /opt/ros/overlay_ws    
          source /opt/ros/overlay_ws/devel/setup.bash 
      - name: Run roscore
        run: |
          roslaunch pycram ik_and_description.launch &           
      - name: Check ros server
        run: |
          apt-get -y install curl 
          curl http://localhost:11311

    

