name: hopeful_CI
defaults:
  run:
    shell: bash -ieo pipefail {0}

on: 
  push:
    branches: 
      - dev
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        required: false
        default: false
        description: 'Run tmate session'

jobs:
  container-test-job:
    runs-on: ubuntu-20.04
    container: 
      image: leoaung/testing_ci:latest
      ports:
        - 11311
    steps:
      - name: Checkout PyCRAM
        uses: actions/checkout@v3
        with: 
          path: 'ros/src/pycram'  
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          submodules: 'recursive'
      - name: Update PyCRAM files
        run: |
          sudo -s
          rm -rf /opt/ros/overlay_ws/src/pycram/* /opt/ros/overlay_ws/src/pycram/.*
          mv /__w/pycram_CI/pycram_CI/ros/src/pycram /opt/ros/overlay_ws/src
      - name: Set up sources & Run roscore
        run: |
          sudo -s
          source /opt/ros/noetic/setup.bash
          cd /opt/ros/overlay_ws
          catkin_make    
          source /opt/ros/overlay_ws/devel/setup.bash 
          roslaunch pycram ik_and_description.launch &           
      - name: Install python dependencies
        run: |
          pip3 install --upgrade pip --root-user-action=ignore
          cd /opt/ros/overlay_ws/src/pycram
          pip3 install -r requirements.txt
          pip3 install --ignore-installed pytest pyjpt mlflow
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}      
      - name: Run tests
        run: |
          sudo -s
          source /opt/ros/noetic/setup.bash
          cd /opt/ros/overlay_ws    
          source /opt/ros/overlay_ws/devel/setup.bash 
          roscd pycram
          pytest -v test  

