name: update_docker_image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
          context: ./docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/testing_ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max