name: update_docker_image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
          file: ./docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/testing_ci:latest


      # - name: Build Docker image
      #   run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/node-example-1 -f docker/Dockerfile

      # - name: Docker push
      #   run: docker push ${{secrets.DOCKERHUB_USERNAME}}/node-example-1
